import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import Hero from "./components/Hero";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define and configure Roboto
const roboto = Roboto({
  weight: ["400", "700"], // Specify the weights you need
  style: ["normal", "italic"], // Specify the styles you need
  subsets: ["latin"],
  variable: "--font-roboto", // Add a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Use the roboto variable in the className */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <div>
          <Hero />
        <Navbar />
        </div>
        
        {children}
      </body>
    </html>
  );
}
